name: Deploy DigitalOcean 

on:
  push:
    branches: 
    - main 
  
jobs:
  build:  
    name: Build and deploy   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Buld Docker Image
        run: docker build -t registry.digitalocean.com/unitcc/tcc-unipar:$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Login Docker
        run: doctl registry login --expire-seconds 600

      - name: Push image
        run: docker push registry.digitalocean.com/unitcc/tcc-unipar:$(echo $GITHUB_SHA | head -c7) .
