name: CI/CD

on:
 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       
       - name: Docker Login
         uses: docker/login-action@v1.12.0
         with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_PWD }}
       - name: Docker Build And Push
         uses: docker/build-push-action@v2.7.0
         with: 
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
           danilocavazim/tcc-unipar:latest
           danilocavazim/tcc-unipar:${{ github.run_number }}
          
  CD:
   needs: [CI]
   runs-on: ubuntu-latest
   
   steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 unicluster

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f k8s/deployment.yaml

    - name: Verify deployment
      run: kubectl rollout status deployment/danilocavazim/tcc-unipar:latest
       
   