name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    name: Generate
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set Package Name and Version
        id: package
        run: |
          echo "::set-output name=name::$(cat ./src/package.json | jq -r '.name')";
          echo "::set-output name=version::$(cat ./src/package.json | jq -r '.version')";

      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 15

      - name: NPM Cache
        uses: c-hive/gha-npm-cache@v1.1.0

      - name: Install Semantic Release Plugins
        run: npm ci

      - name: Generate Release or Pré Release
        run: npx semantic-release --ci
