name: Rollback

on:
  release:
    types: [deleted]

jobs:
  redeploy-production:
    name: Redeploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Latest Relase
        id: release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Checkout Version
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ steps.release.outputs.release }}

      - name: Get Name and Version
        id: package
        run: |
          echo "::set-output name=name::$(cat ./package.json | jq -r '.name')";
          echo "::set-output name=version::$(cat ./package.json | jq -r '.version')";

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Log
        run: |
          echo "${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }}"
      # !TODO: Add cluster and deployment
      # - name: Select Cluster
      #   run: |
      #     gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} \
      #     --zone ${{ secrets.GCP_CLUSTER_ZONE }}
      # - name: Deploy to Staging Cluster
      #   run: |
      #     kubectl set image deployment.apps/starter-microservice \
      #     microservice-starter=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }} --record
